"""empty message

Revision ID: d4b2a6f1e33c
Revises: 
Create Date: 2023-11-23 13:48:56.813350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4b2a6f1e33c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('song',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('artists', sa.String(), nullable=True),
    sa.Column('streams', sa.Integer(), nullable=True),
    sa.Column('bmp', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('danceability', sa.Integer(), nullable=True),
    sa.Column('valence', sa.Integer(), nullable=True),
    sa.Column('energy', sa.Integer(), nullable=True),
    sa.Column('acousticness', sa.Integer(), nullable=True),
    sa.Column('instrumentalness', sa.Integer(), nullable=True),
    sa.Column('liveness', sa.Integer(), nullable=True),
    sa.Column('speechiness', sa.Integer(), nullable=True),
    sa.Column('released_date', sa.String(), nullable=True),
    sa.Column('promotion', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('song_artist',
    sa.Column('song_id', sa.String(), nullable=False),
    sa.Column('artist_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('song_id', 'artist_id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('plan', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('age', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('usage_period', sa.String(), nullable=True),
    sa.Column('listening_scenario', sa.String(), nullable=True),
    sa.Column('fav_music_genre', sa.String(), nullable=True),
    sa.Column('mood', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matchability',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('song_1', sa.String(), nullable=True),
    sa.Column('song_2', sa.String(), nullable=True),
    sa.Column('song_3', sa.String(), nullable=True),
    sa.Column('song_4', sa.String(), nullable=True),
    sa.Column('song_5', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_table('_alembic_tmp_song')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_song',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('artists', sa.VARCHAR(), nullable=True),
    sa.Column('streams', sa.INTEGER(), nullable=True),
    sa.Column('bmp', sa.INTEGER(), nullable=True),
    sa.Column('key', sa.VARCHAR(), nullable=True),
    sa.Column('danceability', sa.INTEGER(), nullable=True),
    sa.Column('valence', sa.INTEGER(), nullable=True),
    sa.Column('energy', sa.INTEGER(), nullable=True),
    sa.Column('acousticness', sa.INTEGER(), nullable=True),
    sa.Column('instrumentalness', sa.INTEGER(), nullable=True),
    sa.Column('liveness', sa.INTEGER(), nullable=True),
    sa.Column('speechiness', sa.INTEGER(), nullable=True),
    sa.Column('released_date', sa.VARCHAR(), nullable=True),
    sa.Column('promotion', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('matchability')
    op.drop_table('user')
    op.drop_table('song_artist')
    op.drop_table('song')
    op.drop_table('artist')
    # ### end Alembic commands ###
